# Generated by Django 3.2.7 on 2021-10-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.IntegerField(default='+234', max_length=11),
        ),
    ]
